language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq astyle
install: bundle install
env:
  - CEEDLING_MAIN_PROJECT_FILE=project.yml
  - CEEDLING_MAIN_PROJECT_FILE=gcc.yml
script: bundle exec rake verbosity[4] test:everything
